---
upstream:
  url: https://github.com/jmfederico/pi-web.git
  ref: v1.202609.0
  patch: 1
targets:
  - name: npm
    image: ghcr.io/raven428/node-builder:latest
    patches: [patches]
    steps:
      - bash scripts/build.sh
