# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
# cspell:ignore mktemp coverprofile covermode dependabot
---
name: repo test
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  tests:
    name: tests
    # jscpd:ignore-start
    if: github.event_name != 'pull_request' ||
      (github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.user.login != 'dependabot[bot]')
    permissions:
      contents: read
    timeout-minutes: 33
    runs-on: ubuntu-24.04
    # jscpd:ignore-end
    steps:
      # jscpd:ignore-start
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false
      - uses: actions/checkout@v7
        with:
          repository: megalomania428/go-lib-ci
          ref: updates-005
          path: go-lib/ci
          persist-credentials: false
      - name: setup go
        uses: actions/setup-go@v7
        with:
          cache: false
          check-latest: false
          go-version-file: golang/go.mod
      # jscpd:ignore-end
      - name: go test
        run: |
          go -C golang mod verify
          go -C golang build ./...
          go -C golang vet ./...
          go -C golang test -race -count=1 -timeout=300s ./...
  linters:
    name: linters
    # jscpd:ignore-start
    if: github.event_name != 'pull_request' ||
      (github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.user.login != 'dependabot[bot]')
    permissions:
      contents: read
    timeout-minutes: 11
    runs-on: ubuntu-24.04
    # jscpd:ignore-end
    steps:
      # jscpd:ignore-start
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false
      # jscpd:ignore-end
      - name: lint the repo
        env:
          BRA: master
          USE_LINTIGNORE: 1
        run: |
          curl -fsL \
          https://raw.githubusercontent.com/raven428/container-images/refs/heads/${{
          env.BRA }}/sources/linters-ubuntu-22_04/check-dir.sh | bash
          curl -fsL \
          https://raw.githubusercontent.com/raven428/container-images/refs/heads/${{
          env.BRA }}/sources/ansible-ubuntu/check-dir.sh | bash
  MegaLinter:
    name: MegaLinter
    # jscpd:ignore-start
    if: github.event_name != 'pull_request' ||
      (github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.user.login != 'dependabot[bot]')
    permissions:
      contents: read
    timeout-minutes: 11
    runs-on: ubuntu-24.04
    # jscpd:ignore-end
    steps:
      # jscpd:ignore-start
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false
      - uses: actions/checkout@v7
        with:
          repository: megalomania428/go-lib-ci
          ref: updates-005
          path: go-lib/ci
          persist-credentials: false
      # jscpd:ignore-end
      - name: Run MegaLinter
        with:
          override_dir: .megalinter/configs
        uses: megalomania428/github-actions/megalinter@master
